timeline
    title Web Development History
    1989 : Tim Berners-Lee invents the World Wide Web
    1995 : Netscape releases JavaScript
         : PHP is created
    2005 : AJAX is coined
         : Git is released by Linus Torvalds
    2013 : React is open-sourced by Facebook